# Generated by Django 3.2.6 on 2021-08-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_pizza_restaurant_place'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owner',
            table='owners',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
